package:
  name: gcc-arm-none-eabi
  version: 10.3.2021.07

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-mac-10.14.6.tar.bz2 # [osx]
  md5: 42d5f143cdc303d73a3602fa5052c790 # [osx]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2 # [linux64]
  md5: b56ae639d9183c340f065ae114a30202 # [linux64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-win32.zip # [win]
  md5: 433921722a948ceb0890edf7826be5b3 # [win]

build:
  number: 0
  binary_relocation: False
  missing_dso_whitelist: '*'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
  license: GPL
  summary: GNU Arm Embedded Toolchain
