package:
  name: gcc-arm-none-eabi
  version: 9.2020.q2.update

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-mac.tar.bz2 # [osx]
  md5: 75a171beac35453fd2f0f48b3cb239c3 # [osx]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 # [linux64]
  md5: 2b9eeccc33470f9d3cda26983b9d2dc6 # [linux64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip # [win]
  md5: 184b3397414485f224e7ba950989aab6 # [win]

build:
  number: 0
  binary_relocation: False
  missing_dso_whitelist: '*'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
  license: GPL
  summary: GNU Arm Embedded Toolchain
